const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
test('1.3 UI uses variant manifest, filters, layered pearl and lock contracts', () => {
  const panel = fs.readFileSync(path.join(root, 'src', 'panel.js'), 'utf8');
  const panelHtml = fs.readFileSync(path.join(root, 'src', 'panel.html'), 'utf8');
  const panelCss = fs.readFileSync(path.join(root, 'src', 'panel-runtime.css'), 'utf8');
  const catalogCss = fs.readFileSync(path.join(root, 'src', 'catalog-runtime.css'), 'utf8');
  const warehouseCss = fs.readFileSync(path.join(root, 'src', 'warehouse-runtime.css'), 'utf8');
  const result = fs.readFileSync(path.join(root, 'src', 'result.js'), 'utf8');
  const resultCss = fs.readFileSync(path.join(root, 'src', 'result.css'), 'utf8');
  const resultRuntimeCss = fs.readFileSync(path.join(root, 'src', 'result-runtime.css'), 'utf8');
  const resultReview = fs.readFileSync(path.join(root, 'scripts', 'capture-result-card-review.js'), 'utf8');
  const renderer = fs.readFileSync(path.join(root, 'src', 'renderer.js'), 'utf8');
  const galleryHtml = fs.readFileSync(path.join(root, 'src', 'iridescent-gallery-v2.2.html'), 'utf8');
  const galleryJs = fs.readFileSync(path.join(root, 'src', 'iridescent-gallery-v2.2.js'), 'utf8');
  assert.match(panel, /id === 'fish-variants'/);
  assert.match(panel, /data-list-field="\$\{field\}"/);
  assert.match(panel, /variants: new Set\(VARIANT_ORDER\)/);
  assert.match(panel, /function variantDetailCards/);
  assert.match(panel, /data-detail-variant/);
  assert.match(panelCss, /\.variant-detail-grid/);
  assert.match(panel, /fish-catalog-card/);
  assert.match(panelHtml, /href="catalog-runtime\.css"/);
  assert.match(panel, /catalog-rarity-band/);
  assert.match(panel, /function catalogPresentation/);
  assert.match(panel, /--catalog-fish-scale/);
  assert.match(panel, /data-catalog-scale="\$\{artScale\}"/);
  assert.match(catalogCss, /\.catalog-grid \.fish-frame\.catalog-compact-art > img/);
  assert.match(catalogCss, /transform:\s*scale\(var\(--catalog-fish-scale, 1\)\)/);
  assert.match(panel, /const variantStatus = allVariants \? status/);
  assert.doesNotMatch(panel, /allVariants \? '变体'/);
  assert.match(catalogCss, /\.catalog-grid \.fish-catalog-card\s*\{[^}]+border-color:\s*var\(--rarity\)/);
  assert.match(catalogCss, /\.variant-text-iridescent[\s\S]+linear-gradient\(90deg, #f8f4ff 0%, #f3a2d1 9%, #b9a2ff 18%, #75e5e2 27%, #ffe18e 37%/);
  assert.match(catalogCss, /catalog-pearl-text-flow 6\.2s steps\(28, end\) -\.75s infinite/);
  assert.match(panelHtml, /href="warehouse-runtime\.css"/);
  assert.match(panel, /inventory-card-head/);
  assert.match(panel, /inventory-rarity/);
  assert.match(panel, /inventory-variant/);
  assert.doesNotMatch(panel, /<span>异色模板<\/span>/);
  assert.match(panel, /class="card-name variant-text-\$\{variant\}"/);
  assert.match(warehouseCss, /box-shadow:\s*inset 0 0 0 3px var\(--rarity\)/);
  assert.match(warehouseCss, /\.inventory-grid \.inventory-card,[\s\S]*?z-index:\s*0;[\s\S]*?isolation:\s*isolate;/);
  assert.match(warehouseCss, /\.inventory-grid \.inventory-variant\s*\{[^}]+justify-content:\s*center/s);
  assert.match(warehouseCss, /\.inventory-rarity\s*\{[^}]+background:\s*var\(--rarity\)/s);
  assert.match(warehouseCss, /\.inventory-grid \.inventory-card \.variant-text-iridescent\s*\{[^}]+linear-gradient\(90deg,\s*#f8f4ff 0%,\s*#f3a2d1 9%,\s*#b9a2ff 18%,\s*#75e5e2 27%,\s*#ffe18e 37%/s);
  assert.match(warehouseCss, /\.inventory-grid \.inventory-card \.variant-text-iridescent\s*\{[^}]+text-shadow:\s*none/s);
  assert.match(panel, /set-inventory-lock/);
  assert.match(panel, /data-action=\\?"toggle-lock\\?"/);
  assert.match(result, /baseIcon/);
  assert.match(result, /bodyMask/);
  assert.match(result, /detailOverlay/);
  assert.match(resultCss, /data-variant="normal"[^}]+color:#aeb8c9/);
  assert.match(resultCss, /data-variant="iridescent"[^}]+linear-gradient\(90deg,#f8f4ff 0%,#f3a2d1 9%,#b9a2ff 18%,#75e5e2 27%,#ffe18e 37%/);
  assert.match(resultCss, /pearl-text-flow 6\.2s steps\(28,end\) -\.75s infinite/);
  assert.match(resultRuntimeCss, /44\.047619vw/);
  assert.match(resultRuntimeCss, /7\.142857vw/);
  assert.match(resultRuntimeCss, /white-space:nowrap/);
  assert.match(resultReview, /runtime-parity-100-vs-135\.png/);
  assert.match(resultReview, /first: true, recordLength: true/);
  assert.match(renderer, /baseAirborneStrip/);
  assert.match(renderer, /airborneMask/);
  assert.match(renderer, /detailOverlayStrip/);
  assert.match(renderer, /baseEntry\.motionData/);
  assert.match(renderer, /airborne-cloud/);
  assert.match(renderer, /airborne-ribbon/);
  assert.match(renderer, /airborne-glint/);
  assert.match(renderer, /maskPosition/);
  assert.match(renderer, /webkitMaskPosition/);
  assert.match(panel, /new IntersectionObserver/);
  assert.match(panel, /getBoundingClientRect/);
  assert.match(galleryHtml, /152 种鱼｜方案 B 珍珠炫彩完整图鉴/);
  assert.match(galleryJs, /PondGame\.FISH/);
  assert.match(galleryJs, /entry\.presentation\.catalogScale/);
});
